using DbSyncEngine.Application.Persistence.Schema;

namespace DbSyncEngine.Infrastructure.Persistence.Schema.Ddl;

public interface ITargetDdlGenerator
{
    /// <summary>Timeout for commands generated by this generator (seconds).</summary>
    int CommandTimeout { get; }

    string GenerateCreateTable(TableDefinition table, string? schema);
    string GenerateCreateTableWithName(TableDefinition table, string tableName, string? schema);
    string GenerateDropTable(string tableName, string? schema);
    string GenerateTableExistsSql(string tableName, string? schema);
    string GenerateTempTableName(string tableName);
    string? GenerateCopyDataSql(string sourceTable, string tempTable, string? schema);
    string GenerateSwapTableSql(string targetTable, string tempTable, string? schema);
    string? GenerateCleanupAfterSwapSql(string targetTable, string tempTable, string? schema);
}